/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inventory.kalerantes;

import java.util.Scanner;

import exceptions.InvalidMenuChoice;
import inventory.menu.Menu;
import inventory.menu.MenuItem;

public class App {

	private static Menu menu = new Menu();

	public static void main(String[] args) {
		ItemList list = new ItemList();

		try (Scanner scanner = new Scanner(System.in)) {
			boolean loop = true;
			while (loop) {
				printMenuOptions();
				String choice = parseInputFromCommandLine(scanner);
				MenuItem menuItemSelected = menu.findByCode(choice);
				menuItemSelected.execute(list, scanner);
			}
		}
	}

	private static void printMenuOptions() {
		System.out.println(menu.options());
	}

	private static String parseInputFromCommandLine(Scanner sc) {
		prompt();
		while(sc.hasNext()) {
			try {
				return validateChoice(sc);
			} catch (Exception e) {
				handleException(e);
			}
			finally {
				prompt();
			}
		}
		return null;
	}

	private static void handleException(Exception e) {
		System.err.println(e.getMessage());
	}

	private static String validateChoice(Scanner sc) {
		String choice = sc.next();
		acceptChoice(choice);
		return choice;
	}

	private static void prompt() {
		System.out.println("Enter choice: ");
	}

	public static void acceptChoice(String choice) {
		validateInBounds(validateInteger(choice));
	}

	private static void validateInBounds(int value) {
		if (value < 1 || value > 6)
			throw new InvalidMenuChoice(String.valueOf(value));
	}

	private static int validateInteger(String choice) {
		try {
			return Integer.parseInt(choice);
		} catch (NumberFormatException e) {
			throw new InvalidMenuChoice(choice);
		}
	}


}
