/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inventory.kalerantes;

import java.io.PrintStream;
import java.util.Scanner;

import inventory.menu.Menu;
import inventory.menu.MenuItem;

public class App {

	private static Menu menu = new Menu();

	public static void main(String[] args) {
		ItemList list = new ItemList();

		try (Scanner scanner = new Scanner(System.in)) {
			boolean loop = true;
			while (loop) {
				printMenuOptions();
				String choice = parseInputFromCommandLine(scanner);
				MenuItem menuItemSelected = menu.findByCode(choice);
				menuItemSelected.execute(list, scanner, System.out);
			}
		}
	}

	private static void printMenuOptions() {
		System.out.println(menu.options());
	}

	private static String parseInputFromCommandLine(Scanner sc) {
		prompt(System.out);
		while(sc.hasNext()) {
			try {
				return validateChoice(sc);
			} catch (Exception e) {
				handleException(e);
			}
			finally {
				prompt(System.out);
			}
		}
		return null;
	}

	private static void handleException(Exception e) {
		System.err.println(e.getMessage());
	}

	private static String validateChoice(Scanner sc) {
		String choice = sc.next();
		new CLIMenuChoiceValidator().validate(choice);
		return choice;
	}

	private static void prompt(PrintStream out) {
		out.println("Enter choice: ");
	}

}
