/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inventory.kalerantes;

public class App {


	public static void main(String[] args) {
		new UI().run(System.in, System.out, System.err);
	}

}
