/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intentory.kalerantes;

import java.util.Scanner;

import exceptions.InvalidMenuChoice;
import formats.CsvFormat;
import formats.HtmlFormat;
import formats.JsonFormat;

public class App {

	private static Menu menu = new Menu();

	public static void main(String[] args) {
		ItemList list = new ItemList();
		HtmlFormat htmlformatter = new HtmlFormat(list);
		CsvFormat csvFormatter = new CsvFormat(list);
		JsonFormat jFormat = new JsonFormat(list);

		try (Scanner scanner = new Scanner(System.in)) {
			boolean loop = true;
			while (loop) {
				printMenuOptions();
				String choice = parseInputFromCommandLine(scanner);
				MenuItem menuItemSelected = menu.findByCode(choice);
				menuItemSelected.execute(list);

				if ("1".equals(choice)) {
					scanner.nextLine();
					list.addItem(scanner);
				}
				if ("2".equals(choice)) {
					systemOutPrintHtml(htmlformatter);
				}
				if ("3".equals(choice)) {
					htmlformatter.createHtmlFile();
				}
				if ("4".equals(choice)) {
					systemOutPrintCsv(csvFormatter);
				}
				if ("5".equals(choice)) {
					jFormat.createFileWithJsonFormat();
				}

			}
		}

	}

	private static void printMenuOptions() {
		System.out.println(menu.options());
	}

	private static String parseInputFromCommandLine(Scanner sc) {
		prompt();
		while(sc.hasNext()) {
			try {
				return validateChoice(sc);
			} catch (Exception e) {
				handleException(e);
			}
			finally {
				prompt();
			}
		}
		return null;
	}

	private static void handleException(Exception e) {
		System.err.println(e.getMessage());
	}

	private static String validateChoice(Scanner sc) {
		String choice = sc.next();
		acceptChoice(choice);
		return choice;
	}

	private static void prompt() {
		System.out.println("Enter choice: ");
	}

	public static void acceptChoice(String choice) {
		validateInBounds(validateInteger(choice));
	}

	private static void validateInBounds(int value) {
		if (value < 1 || value > 6)
			throw new InvalidMenuChoice(String.valueOf(value));
	}

	private static int validateInteger(String choice) {
		try {
			return Integer.parseInt(choice);
		} catch (NumberFormatException e) {
			throw new InvalidMenuChoice(choice);
		}
	}

	private static void systemOutPrintHtml(HtmlFormat htmlformat) {
		System.out.println("INVETORY HTML REPORT");
		System.out.println("********************");
		System.out.println(htmlformat.printHtml());
	}

	private static void systemOutPrintCsv(CsvFormat csvFormatter) {
		System.out.println("INVETORY CSV REPORT");
		System.out.println("********************");
		System.out.println(csvFormatter.printCsv() + "\n");
	}

	private static boolean exitProgram() {
		System.out.println("BYE BYE!!!");
		return false;
	}
}
