/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package inventory.kalerantes

import exceptions.InvalidMenuChoice
import spock.lang.Specification
import spock.lang.Unroll

class AppTest extends Specification {

	//TODO the following two test are Integration tests. They can be simplified when app class is simplified
	@Unroll
	def "accept input throws exception if not between 1 and 6"() {
		given:
		def input = new ByteArrayInputStream((choice + System.lineSeparator() ).getBytes());
		Scanner scanner = new Scanner(input)

		when:
		App.validateChoice(scanner)

		then:
		def e = thrown(InvalidMenuChoice)
		e.message == "Expected value between 1 and 6 but got ${choice} instead."

		where:
		choice << ["a", "asdfasdgfasdg", "112", "0", null]
	}

	@Unroll
	def "accept input only between 1 and 6" () {
		given:
		def input = new ByteArrayInputStream((choice + System.lineSeparator() ).getBytes());
		Scanner scanner = new Scanner(input)

		when:
		App.validateChoice(scanner)

		then:
		notThrown(InvalidMenuChoice)

		where:
		choice << ("1".."6")
	}

	def prompt() {
		OutputStream captureOutput = new ByteArrayOutputStream()
		PrintStream out = new PrintStream(captureOutput)

		when:
		App.prompt(out)

		then:
		captureOutput.toString() == "Enter choice: ${System.lineSeparator()}"
	}

}
