/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package intentory.kalerantes

import exceptions.InvalidMenuChoice
import spock.lang.Specification
import spock.lang.Unroll

class AppTest extends Specification {

	@Unroll
	def "accept input throws exception if not between 1 and 6"() {
		when:
		App.acceptChoice(choice)

		then:
		def e = thrown(InvalidMenuChoice)
		e.message == "Expected value between 1 and 6 but got ${choice} instead."

		where:
		choice << ["a", "asdfasdgfasdg", "112", "0", null]
	}

	@Unroll
	def "accept input only between 1 and 6" () {
		when:
		App.acceptChoice(choice)

		then:
		notThrown(InvalidMenuChoice)

		where:
		choice << ("1".."6")
	}

}
